env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
#  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
rules:
  semi:
    - 2
    - never
  prettier/prettier:
    - error
    - singleQuote: true
      semi: false
